### ISSUE TITLE
The `build_release.sh` does not validate export templates version

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-build-scripts#40]
If you look at:

https://github.com/godotengine/godot-build-scripts/blob/f6ddb4e192177c89dc53c0696380aac20d774e0b/build-release.sh#L108-L109

You can see a difference that export templates version uses dot `.` over hyphen `-`. This is inconsistent, and if you make a copy-paste mistake, this will lead to broken process of installing templates from a `tpz` file in the editor. The error is possible to recover by modifying `version.txt` inside the `tpz` file, but doing so would result in checksum mismatches which must also be recalculated after the modification.

So, I think `build_release.sh` should validate the version for export templates, at the very least.

**Comment by Xrayez** [comment]
I've been waiting for this issue to get fixed, and it got finally fixed! https://github.com/godotengine/godot-build-scripts/commit/45abfae75fd5ab77bc259aa59cbc93ce7ee1f399

My prophecy came true.

**Comment by akien-mga** [comment]
Ah yes, I could have done this earlier but forgot to. Eventually did so after being bitten by the lack of check myself :D
