### ISSUE TITLE
Expose the Godot Android library

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot-build-scripts#6]
As mentioned in the [Godot Android plugin documentation](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html#android-plugin), the Godot Android library generated by the Android build as `godot-lib.release.aar` must be exposed for use by plugin developers.

When made available for download, the library should be renamed to refer to the Godot version it's for (e.g: `godot-lib.3.2.2.release.aar`)

**Comment by akien-mga** [comment]
You can test with 3.2.2 beta 3 to confirm that it works as intended: https://downloads.tuxfamily.org/godotengine/3.2.2/beta3/

I assumed that only the version number should be included and not the `.beta3` part.

**Comment by m4gr3d** [comment]
We can include the `.beta3` part to remind plugin developers that it's not the final library file, and that it'll need to be updated when the final stable version comes out. Otherwise I can see a few forgetting that the one they have is a `beta` version and not the final one.

Do you know if it would be possible to have a direct link for it when the final stable `3.2.2` version comes out? 
It's so I can update the documentation with that link so that plugin developers can easily find it.

**Comment by akien-mga** [comment]
> We can include the `.beta3` part to remind plugin developers that it's not the final library file, and that it'll need to be updated when the final stable version comes out. Otherwise I can see a few forgetting that the one they have is a `beta` version and not the final one.

Alright, I'll add it in the next builds. But then the best would be that the expected canonical name should always be `version.status` like for the export templates, e.g. `3.2.2.beta3` and `3.2.2.stable` (so also with `.stable` for the final build).

The documentation page does not mention the `.release` part BTW. And does this naming scheme correspond to some lookup logic which is hardcoded in the plugin system, or is it just cosmetic/for documentation purposes?

> Do you know if it would be possible to have a direct link for it when the final stable `3.2.2` version comes out?
> It's so I can update the documentation with that link so that plugin developers can easily find it.

A direct link to e.g. https://downloads.tuxfamily.org/godotengine/3.2.2/beta3/godot-lib.3.2.2.release.aar would need to be updated every single time we release a new version, so it's probably best not to include it in the docs. But we could put a link on the download page: https://godotengine.org/download and you can refer to that page to download the plugin for the latest stable release.
