### ISSUE TITLE
Windows console scripts do not match the engine provided ones

### ISSUE THREAD

**Issue by Macksaur** [godotengine/godot-build-scripts#61]
https://github.com/godotengine/godot-build-scripts/blob/8405945b7990f1bef6e0afab3bbfa7749d6b10fb/build-release.sh#L200

https://github.com/godotengine/godot/blob/5a8d786ef9dcfd5b206ec3eeb5e369930e773acc/platform/windows/export/export_plugin.cpp#L53

This is an issue because it prevents things like opening projects quickly with the desired editor version by dragging and dropping `project.godot` onto the respective script.

In order for the console scripts to be useful beyond launching the project manager they need to support passing arguments.

**Comment by Calinou** [comment]
> In order for the console scripts to be useful beyond launching the project manager they need to support passing arguments.

This is done by passing `"$@"` after `${binname}`.

**Comment by Macksaur** [comment]
```
@echo off
Godot_v3.5-stable_win64.exe
pause > nul
```

for context, this is what is in the official zip.

**Comment by akien-mga** [comment]
Sorry for the delay. The suggestion was good, but it's not longer relevant as we replaced these batch scripts by wrapper executables.
