### ISSUE TITLE
Update ANGLE and GLES libraries for UWP

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-build-scripts#80]
As documented by @panreyes in https://github.com/godotengine/godot/issues/9168#issuecomment-1619337877, replacing the `libGLESv2.dll` and `libEGL.dll` libraries with versions from https://www.nuget.org/api/v2/package/ANGLE.WindowsStore/2.1.13 solves https://github.com/godotengine/godot/issues/9168 for UWP.

This would be worth doing for future 3.x builds.

We may also consider updating ANGLE itself, as we're still using a build from 2017.

**Comment by panreyes** [comment]
The nuget package DLLs are a bit newer (2.1.13 > 2.1.0) than what Godot currently uses, and, as far as I have tested (3 2D games, a few hours each on a Xbox Series S), it seems to be working correctly and that its ABI is compatible.

Updating Godot to support current ANGLE (current Chromium's version) would be the ideal scenario, but it will probably require a lot of work and it won't be helpful for Godot 4.x. 

I would suggest a quick 5 minute fix: to just update the DLL files used by the UWP automated builds (from this file https://github.com/GodotBuilder/godot-builds/releases/download/_tools/angle.7z
 ) and regenerating the related export templates (or even just replacing the DLLs in the tgz files manually for the current templates, if that's faster).

All the required files are in the nuget package, at least to generate the updated UWP template :)

**Comment by akien-mga** [comment]
Fixed by #85.
